export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)" },

  { id: 2, bgcolor: "linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)" },

  { id: 3, bgcolor: "linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)" },

  { id: 4, bgcolor: "linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)" },

  { id: 5, bgcolor: "linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)" },

  { id: 6, bgcolor: "linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)" },

  { id: 7, bgcolor: "linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)" },

  { id: 8, bgcolor: "linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)" },

  { id: 9, bgcolor: "linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)" },

  { id: 10, bgcolor: "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)" },
];

export const APP_FEATURES = [
  {
    id: 1,
    title: "Tailored just for You",
    description:
      "Get personalized interview questions and model based answers on your role, experience, profile and specific focus areas.",
  },
  {
    id: 2,
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you are ready. Dive deeper into topics instantly with our expandable answer feature.",
  },

  {
    id: 3,
    title: "Capture Your Insights.",
    description:
      "Add your own notes and insights to each question. Keep track of your learning journey and revisit your thoughts anytime.",
  },
  {
    id: 4,
    title: 'Understand the "Why" Behind Each Answer',
    description:
      "Gain deeper insights into the reasoning behind each answer. Our explanations generated by AI help you grasp concepts better and apply them effectively.",
  },
  {
    id: 5,
    title: "Save, Organize and revisit",
    description:
      "Easily save your interview sets. Organize them neatly in your dashboard for quick access. Revisit your saved sets anytime to refresh your knowledge.",
  },
];
