export const APP_FEATURES = [
  {
    id: 1,
    title: "Tailored just for You",
    description:
      "Get personalized interview questions and model based answers on your role, experience, profile and specific focus areas.",
  },
  {
    id: 2,
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you are ready. Dive deeper into topics instantly with our expandable answer feature.",
  },

  {
    id: 3,
    title: "Capture Your Insights.",
    description:
      "Add your own notes and insights to each question. Keep track of your learning journey and revisit your thoughts anytime.",
  },
  {
    id: 4,
    title: 'Understand the "Why" Behind Each Answer',
    description:
      "Gain deeper insights into the reasoning behind each answer. Our explanations generated by AI help you grasp concepts better and apply them effectively.",
  },
  {
    id: 5,
    title: "Save, Organize and revisit",
    description:
      "Easily save your interview sets. Organize them neatly in your dashboard for quick access. Revisit your saved sets anytime to refresh your knowledge.",
  },
];
